---

  # We are running as normal user, cannot use apt: module here
- name: Install cryptsetup if not installed
  shell: sudo apt-get -yq install cryptsetup creates=/etc/default/cryptdisks
  changed_when: False
  tags: secret


