---

- include: check.yml
  when: secret is defined and secret

- include: init.yml
  when: secret is defined and secret

- include: close.yml
  when: secret is defined and secret

- include: setup.yml
  when: secret is defined and secret

- include: open.yml
  when: secret is defined and secret and secret_mode is defined and secret_mode == 'open'

