---

- name: Open storage space
  shell: gpg --decrypt {{ secret }}/{{ secret_keyfile }} | sudo cryptsetup luksOpen {{ secret }}/{{ secret_storage }} {{ secret_device }} executable={{ lookup('env', 'SHELL') }} creates=/dev/mapper/{{ secret_device }}
  changed_when: False
  tags: secret

- name: Mount storage device
  shell: sudo mount /dev/mapper/{{ secret_device }} {{ secret }}
  register: secret_device_mounted
  changed_when: "secret_device_mounted.rc != 0"
  tags: secret

- name: Fix storage device permissions
  shell: "sudo chown {{ lookup('env','USER') }}:{{ lookup('env','USER') }} {{ secret }} && sudo chmod 700 {{ secret }}"
  changed_when: False
  tags: secret

